### PR TITLE
Auto-translated international channel support

### PR DESCRIPTION
**Pull request by Epicpkmn11**
This adds handling for "international" channels which function as a pair of one channel where non-English languages are allowed and one channel where only English is used, primarily for ease of moderation.

Any message sent to the international channel will be automatically translated to English, if needed messages can also be sent in the English channel as either replies to an autotranslated message or starting with "language code:" (ex. "ja: hello") to be translated back to that language in the international channel.

### CODE REVIEW

**Comment by Epicpkmn11** [comment]
Should be good now I think. Just need to get a DeepL token and update the config, can use mine if needed but since I use that in a couple other places I think it would be ideal to have one specifically for this.

> 👎 2

imo we should at least give this a try for a few weeks or so and see how it goes. It's not that infrequent for there to be language barrier issues in #nds-modding-help and there's quite a few people on the server who can speak multiple languages so it'd just work a lot better to allow helping out in other languages without needing for it to be a big hassle.

Even if people talk via the auto machine translation (which ideally shouldn't happen much) it can still be better than copy pasting between google/deepl translate as it's A) easier and B) you can see what they actually meant, even if you don't understand the language you may be able to tell where machine translation is failing if they say something nonsensical.

**Comment by LightSage** [comment]
I don't mind a trial run. My real issue with is this should probably be something private (i.e. on a case by case basis). I'd rather not promote the server being an international server just because of the fact that DeepL translations are usually okay. I use the word promote because more than likely users who come here speaking (let's say Spanish [or]) other languages will start telling their friends "Hey DSi Server can help in Spanish now"

**Comment by Epicpkmn11** [comment]
The DeepL features are primarily aimed at making the channel moderatable, more so than helping using it ideally.

Is it really a bad thing if it becomes known that we offer support in Spanish and such? I guess it might lead to a bit of people trying to use Spanish outside of the help channel, but I'm not suggesting we remove rule 6 or anything (just need to exclude #nds-help-international), and I'd much rather people come to our Discord for help than the comments on some random Spanish vguide or such.

**Comment by lifehackerhansol** [comment]
Closing due to lack of interest.

**Pull request closed without merging**
